FROM jupyter/all-spark-notebook:spark-3.5.0

USER root

# Скачиваем КОМПЛЕКТ драйверов во время сборки образа
RUN wget https://repo1.maven.org/maven2/org/apache/spark/spark-sql-kafka-0-10_2.12/3.5.0/spark-sql-kafka-0-10_2.12-3.5.0.jar -P /usr/local/spark/jars/ && \
  wget https://repo1.maven.org/maven2/org/apache/kafka/kafka-clients/3.4.1/kafka-clients-3.4.1.jar -P /usr/local/spark/jars/ && \
  wget https://repo1.maven.org/maven2/org/apache/spark/spark-token-provider-kafka-0-10_2.12/3.5.0/spark-token-provider-kafka-0-10_2.12-3.5.0.jar -P /usr/local/spark/jars/ && \
  wget https://repo1.maven.org/maven2/org/postgresql/postgresql/42.5.0/postgresql-42.5.0.jar -P /usr/local/spark/jars/ && \
  wget https://repo1.maven.org/maven2/org/apache/commons/commons-pool2/2.11.1/commons-pool2-2.11.1.jar -P /usr/local/spark/jars/

USER ${NB_UID}
